os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
  - name: "checks"
    script:
    - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t kam1runetz/bootstrap-cpp scripts/checks.sh
  - name: "tests"
    script:
    - docker run -v `pwd`:`pwd` -w `pwd` -t kam1runetz/bootstrap-cpp scripts/tests.sh
  - name: "quality"
    script:
    - ./scripts/genenv.sh
    - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t kam1runetz/bootstrap-cpp scripts/coverage.sh

notifications:
    email: 
      - notsoserious2017@gmail.com

branches:
  only:
  - development
